version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - PEACH_USER=${PEACH_USER}
      - PEACH_PASS=${PEACH_PASS}
    volumes:
      - ./data:/app/data
      - ./database.sqlite:/app/database.sqlite
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    restart: unless-stopped

  client-portal:
    build:
      context: ./client-portal
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    restart: unless-stopped 